### PR TITLE
👌 Improved Ruby Syntax

### PR DESCRIPTION
**Pull request by clouby**
Hi @ahmadawais, I've made some improvement about ruby syntax, hope you like it.

### CODE REVIEW

**Comment by ahmadawais** [comment]
🙌 can we have a screenshot :)👌

**Comment by clouby** [comment]
sure!! 😄 

ruby_sop

**Comment by clouby** [comment]
Test now. 👍  (Not a ruby dev ? 😕)

**Comment by ahmadawais** [comment]
Kindly, use [Emoji Log](https://github.com/ahmadawais/Emoji-Log) for all commits.

**Comment by ahmadawais** [comment]
Thank You! 😇
Keep improving.

**Pull request merged**
